apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: docker.aic.gov.eg/dev/mern-project-backend:v2.0.5
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        volumeMounts:
        - name: uploads-storage
          mountPath: /uploads/images
      volumes:
      - name: uploads-storage
        emptyDir: {}
      imagePullSecrets:
      - name: my-registry-secret